/**
 * Google Play wording shown only in the Android app. The existing App Store
 * wording (premium.*, paywall.*) is untouched and still used on iOS and web.
 *
 * Google Play purchases are not implemented yet, so every text here states
 * that purchasing is not available in this Android version.
 */
export type AndroidStoreCopy = {
  unavailable: string;
  appOnly: string;
  priceUnavailable: string;
  purchasing: string;
  storeNote: string;
};

export const ANDROID_STORE_KEYS = ["unavailable", "appOnly", "priceUnavailable", "purchasing", "storeNote"] as const;

export const androidStoreTranslations: Record<string, AndroidStoreCopy> = {
  sv: { unavailable: "Köp via Google Play är inte tillgängliga i den här Android-versionen ännu.", appOnly: "Köp via Google Play kommer snart och är inte tillgängliga i den här Android-versionen ännu.", priceUnavailable: "Priset kan inte hämtas från Google Play just nu. Försök igen.", purchasing: "Öppnar Google Play…", storeNote: "Hanteras av Google Play." },
  en: { unavailable: "Purchases via Google Play are not available in this Android version yet.", appOnly: "Purchases via Google Play are coming soon and are not available in this Android version yet.", priceUnavailable: "Can’t fetch the price from Google Play right now. Try again.", purchasing: "Opening Google Play…", storeNote: "Handled by Google Play." },
  fi: { unavailable: "Google Play -ostot eivät ole vielä käytettävissä tässä Android-versiossa.", appOnly: "Google Play -ostot ovat tulossa pian, eivätkä ne ole vielä käytettävissä tässä Android-versiossa.", priceUnavailable: "Hintaa ei voida hakea Google Playsta juuri nyt. Yritä uudelleen.", purchasing: "Avataan Google Play…", storeNote: "Käsittelee Google Play." },
  da: { unavailable: "Køb via Google Play er endnu ikke tilgængelige i denne Android-version.", appOnly: "Køb via Google Play kommer snart og er endnu ikke tilgængelige i denne Android-version.", priceUnavailable: "Prisen kan ikke hentes fra Google Play lige nu. Prøv igen.", purchasing: "Åbner Google Play…", storeNote: "Håndteres af Google Play." },
  de: { unavailable: "Käufe über Google Play sind in dieser Android-Version noch nicht verfügbar.", appOnly: "Käufe über Google Play kommen bald und sind in dieser Android-Version noch nicht verfügbar.", priceUnavailable: "Der Preis kann gerade nicht von Google Play abgerufen werden. Bitte erneut versuchen.", purchasing: "Google Play wird geöffnet…", storeNote: "Abgewickelt über Google Play." },
  cs: { unavailable: "Nákupy přes Google Play zatím nejsou v této verzi pro Android dostupné.", appOnly: "Nákupy přes Google Play budou brzy k dispozici; v této verzi pro Android zatím nejsou dostupné.", priceUnavailable: "Cenu teď nelze načíst z Google Play. Zkuste to znovu.", purchasing: "Otevírá se Google Play…", storeNote: "Zajišťuje Google Play." },
  pl: { unavailable: "Zakupy przez Google Play nie są jeszcze dostępne w tej wersji na Androida.", appOnly: "Zakupy przez Google Play pojawią się wkrótce i nie są jeszcze dostępne w tej wersji na Androida.", priceUnavailable: "Nie można teraz pobrać ceny z Google Play. Spróbuj ponownie.", purchasing: "Otwieranie Google Play…", storeNote: "Obsługiwane przez Google Play." },
  sk: { unavailable: "Nákupy cez Google Play zatiaľ nie sú v tejto verzii pre Android dostupné.", appOnly: "Nákupy cez Google Play budú čoskoro k dispozícii; v tejto verzii pre Android zatiaľ nie sú dostupné.", priceUnavailable: "Cenu teraz nemožno načítať z Google Play. Skúste to znova.", purchasing: "Otvára sa Google Play…", storeNote: "Zabezpečuje Google Play." },
  sl: { unavailable: "Nakupi prek Google Play v tej različici za Android še niso na voljo.", appOnly: "Nakupi prek Google Play bodo kmalu na voljo; v tej različici za Android še niso omogočeni.", priceUnavailable: "Cene trenutno ni mogoče pridobiti iz Google Play. Poskusite znova.", purchasing: "Odpiranje Google Play…", storeNote: "Upravlja Google Play." },
  et: { unavailable: "Google Play ostud pole selles Androidi versioonis veel saadaval.", appOnly: "Google Play ostud tulevad peagi ega ole selles Androidi versioonis veel saadaval.", priceUnavailable: "Hinda ei saa praegu Google Playst laadida. Proovi uuesti.", purchasing: "Google Play avamine…", storeNote: "Haldab Google Play." },
  lv: { unavailable: "Pirkumi Google Play vēl nav pieejami šajā Android versijā.", appOnly: "Pirkumi Google Play drīzumā būs pieejami; šajā Android versijā tie vēl nav pieejami.", priceUnavailable: "Pašlaik nevar iegūt cenu no Google Play. Mēģiniet vēlreiz.", purchasing: "Atver Google Play…", storeNote: "Apstrādā Google Play." },
  lt: { unavailable: "Pirkimai per Google Play šioje Android versijoje dar negalimi.", appOnly: "Pirkimai per Google Play netrukus bus prieinami; šioje Android versijoje jų dar nėra.", priceUnavailable: "Šiuo metu nepavyksta gauti kainos iš Google Play. Bandykite dar kartą.", purchasing: "Atidaroma Google Play…", storeNote: "Tvarko Google Play." },
  fr: { unavailable: "Les achats via Google Play ne sont pas encore disponibles dans cette version Android.", appOnly: "Les achats via Google Play arrivent bientôt et ne sont pas encore disponibles dans cette version Android.", priceUnavailable: "Impossible de récupérer le prix sur Google Play pour le moment. Réessayez.", purchasing: "Ouverture de Google Play…", storeNote: "Géré par Google Play." },
  it: { unavailable: "Gli acquisti tramite Google Play non sono ancora disponibili in questa versione Android.", appOnly: "Gli acquisti tramite Google Play arriveranno presto e non sono ancora disponibili in questa versione Android.", priceUnavailable: "Impossibile recuperare il prezzo da Google Play in questo momento. Riprova.", purchasing: "Apertura di Google Play…", storeNote: "Gestito da Google Play." },
  es: { unavailable: "Las compras a través de Google Play aún no están disponibles en esta versión de Android.", appOnly: "Las compras a través de Google Play llegarán pronto y aún no están disponibles en esta versión de Android.", priceUnavailable: "No se puede obtener el precio de Google Play en este momento. Inténtalo de nuevo.", purchasing: "Abriendo Google Play…", storeNote: "Gestionado por Google Play." },
  pt: { unavailable: "As compras através do Google Play ainda não estão disponíveis nesta versão Android.", appOnly: "As compras através do Google Play estarão disponíveis em breve e ainda não existem nesta versão Android.", priceUnavailable: "Não é possível obter o preço do Google Play neste momento. Tente novamente.", purchasing: "A abrir o Google Play…", storeNote: "Gerido pelo Google Play." },
  nl: { unavailable: "Aankopen via Google Play zijn nog niet beschikbaar in deze Android-versie.", appOnly: "Aankopen via Google Play komen binnenkort en zijn nog niet beschikbaar in deze Android-versie.", priceUnavailable: "De prijs kan nu niet via Google Play worden opgehaald. Probeer het opnieuw.", purchasing: "Google Play wordt geopend…", storeNote: "Afgehandeld door Google Play." },
  no: { unavailable: "Kjøp via Google Play er ikke tilgjengelig i denne Android-versjonen ennå.", appOnly: "Kjøp via Google Play kommer snart og er ikke tilgjengelig i denne Android-versjonen ennå.", priceUnavailable: "Prisen kan ikke hentes fra Google Play akkurat nå. Prøv igjen.", purchasing: "Åpner Google Play…", storeNote: "Håndteres av Google Play." },
  ro: { unavailable: "Achizițiile prin Google Play nu sunt încă disponibile în această versiune Android.", appOnly: "Achizițiile prin Google Play vor fi disponibile în curând; în această versiune Android nu sunt încă disponibile.", priceUnavailable: "Prețul nu poate fi obținut acum din Google Play. Încercați din nou.", purchasing: "Se deschide Google Play…", storeNote: "Gestionat de Google Play." },
  el: { unavailable: "Οι αγορές μέσω Google Play δεν είναι ακόμη διαθέσιμες σε αυτή την έκδοση Android.", appOnly: "Οι αγορές μέσω Google Play έρχονται σύντομα και δεν είναι ακόμη διαθέσιμες σε αυτή την έκδοση Android.", priceUnavailable: "Δεν είναι δυνατή η λήψη της τιμής από το Google Play αυτή τη στιγμή. Δοκιμάστε ξανά.", purchasing: "Άνοιγμα Google Play…", storeNote: "Διεκπεραιώνεται από το Google Play." },
  hu: { unavailable: "A Google Play-vásárlások ebben az Android-verzióban még nem érhetők el.", appOnly: "A Google Play-vásárlások hamarosan elérhetők lesznek; ebben az Android-verzióban még nem használhatók.", priceUnavailable: "Az árat most nem lehet lekérni a Google Playről. Próbálja újra.", purchasing: "Google Play megnyitása…", storeNote: "A Google Play kezeli." },
  hr: { unavailable: "Kupnje putem Google Playa još nisu dostupne u ovoj Android verziji.", appOnly: "Kupnje putem Google Playa uskoro stižu i još nisu dostupne u ovoj Android verziji.", priceUnavailable: "Cijenu trenutno nije moguće dohvatiti s Google Playa. Pokušajte ponovno.", purchasing: "Otvaranje Google Playa…", storeNote: "Obrađuje Google Play." },
  sr: { unavailable: "Kupovine preko Google Play-a još nisu dostupne u ovoj Android verziji.", appOnly: "Kupovine preko Google Play-a uskoro stižu i još nisu dostupne u ovoj Android verziji.", priceUnavailable: "Cenu trenutno nije moguće preuzeti sa Google Play-a. Pokušajte ponovo.", purchasing: "Otvaranje Google Play-a…", storeNote: "Obrađuje Google Play." },
  bg: { unavailable: "Покупките чрез Google Play все още не са налични в тази версия за Android.", appOnly: "Покупките чрез Google Play предстоят скоро и все още не са налични в тази версия за Android.", priceUnavailable: "В момента цената не може да бъде получена от Google Play. Опитайте отново.", purchasing: "Отваряне на Google Play…", storeNote: "Обработва се от Google Play." },
  uk: { unavailable: "Покупки через Google Play ще недоступні в цій версії для Android.", appOnly: "Покупки через Google Play з’являться незабаром і ще недоступні в цій версії для Android.", priceUnavailable: "Зараз не вдається отримати ціну з Google Play. Спробуйте ще раз.", purchasing: "Відкриваємо Google Play…", storeNote: "Обробляється Google Play." },
  tr: { unavailable: "Google Play üzerinden satın alma bu Android sürümünde henüz kullanılamıyor.", appOnly: "Google Play üzerinden satın alma yakında geliyor; bu Android sürümünde henüz kullanılamıyor.", priceUnavailable: "Fiyat şu anda Google Play'den alınamıyor. Tekrar deneyin.", purchasing: "Google Play açılıyor…", storeNote: "Google Play tarafından yönetilir." },
  hi: { unavailable: "Google Play के ज़रिए ख़रीदारी इस Android संस्करण में अभी उपलब्ध नहीं है।", appOnly: "Google Play के ज़रिए ख़रीदारी जल्द आ रही है और इस Android संस्करण में अभी उपलब्ध नहीं है।", priceUnavailable: "अभी Google Play से कीमत प्राप्त नहीं हो सकी। फिर से प्रयास करें।", purchasing: "Google Play खोला जा रहा है…", storeNote: "Google Play द्वारा प्रबंधित।" },
  id: { unavailable: "Pembelian melalui Google Play belum tersedia di versi Android ini.", appOnly: "Pembelian melalui Google Play segera hadir dan belum tersedia di versi Android ini.", priceUnavailable: "Harga tidak dapat diambil dari Google Play saat ini. Coba lagi.", purchasing: "Membuka Google Play…", storeNote: "Ditangani oleh Google Play." },
  he: { unavailable: "רכישות דרך Google Play עדיין אינן זמינות בגרסת Android זו.", appOnly: "רכישות דרך Google Play יגיעו בקרוב ועדיין אינן זמינות בגרסת Android זו.", priceUnavailable: "לא ניתן לקבל את המחיר מ-Google Play כרגע. נסו שוב.", purchasing: "פותח את Google Play…", storeNote: "מטופל על ידי Google Play." },
};

type StoreKey = (typeof ANDROID_STORE_KEYS)[number];

/**
 * Returns the translation key for a store text: the Google Play variant in the
 * Android app, the existing App Store key everywhere else (iOS, web).
 */
export function storeTextKey(isAndroid: boolean, key: StoreKey, appleKey: string): string {
  return isAndroid ? `androidStore.${key}` : appleKey;
}
