import type { HourlyProfile } from "@/lib/calc/hourly-comparison";

type ProfileCopy = {
  profileOverview: string;
  profileAssumption: string;
  profileChartAria: string;
  profileTable: string;
  hour: string;
  total: string;
  profileDescription: Record<HourlyProfile, string>;
};

export const hourlyProfileTranslations: Record<string, ProfileCopy> = {
  sv:{profileOverview:"Schablonernas dygnskurvor",profileAssumption:"Kurvorna är begripliga schabloner, inte uppmätta eller kalibrerade förbrukningsmönster. Samma kurva används alla veckodagar.",profileChartAria:"Fyra schablonkurvor för förbrukning över dygnets timmar",profileTable:"Andel av ett normalt dygn",hour:"Timme",total:"Summa",profileDescription:{evening:"Nattlig baslast, morgontopp, lägre förbrukning dagtid och tydlig kvällstopp.",mixed:"Förbrukning hela dygnet med måttliga morgon- och kvällstoppar.",daytime:"Låg nattförbrukning och en större, jämnt fördelad andel under dagtid.",uniform:"Samma förbrukning varje timme inom månaden; månadernas energimängder är fortfarande olika."}},
  en:{profileOverview:"Daily standard profiles",profileAssumption:"These curves are simple assumptions, not measured or calibrated consumption patterns. The same curve is used every day of the week.",profileChartAria:"Four standard consumption curves across the hours of a day",profileTable:"Share of a typical day",hour:"Hour",total:"Total",profileDescription:{evening:"Night-time base load, a morning peak, lower daytime use and a clear evening peak.",mixed:"Consumption throughout the day with moderate morning and evening peaks.",daytime:"Low night-time use and a larger, evenly spread share during daytime.",uniform:"The same consumption every hour within a month; monthly energy totals still differ."}},
  fi:{profileOverview:"Vuorokauden vakioprofiilit",profileAssumption:"Käyrät ovat yksinkertaistettuja oletuksia, eivät mitattuja tai kalibroituja kulutusmalleja. Samaa käyrää käytetään viikon jokaisena päivänä.",profileChartAria:"Neljä vuorokautista kulutuksen vakiokäyrää",profileTable:"Osuus tavallisesta vuorokaudesta",hour:"Tunti",total:"Yhteensä",profileDescription:{evening:"Yön peruskuorma, aamuhuippu, vähäisempi päiväkulutus ja selkeä iltahuippu.",mixed:"Kulutusta koko päivän sekä kohtuulliset aamu- ja iltahuiput.",daytime:"Vähäinen yökulutus ja suurempi tasainen osuus päiväsaikaan.",uniform:"Sama kulutus kuukauden jokaisena tuntina; kuukausien energiamäärät eroavat silti."}},
  da:{profileOverview:"Døgnets standardprofiler",profileAssumption:"Kurverne er enkle antagelser, ikke målte eller kalibrerede forbrugsmønstre. Samme kurve bruges alle ugens dage.",profileChartAria:"Fire standardkurver for forbrug gennem døgnet",profileTable:"Andel af et normalt døgn",hour:"Time",total:"I alt",profileDescription:{evening:"Grundforbrug om natten, morgentop, lavere forbrug om dagen og tydelig aftentop.",mixed:"Forbrug hele døgnet med moderate morgen- og aftentoppe.",daytime:"Lavt natforbrug og en større, jævnt fordelt andel om dagen.",uniform:"Samme forbrug hver time i måneden; månedsenergien varierer stadig."}},
  de:{profileOverview:"Standard-Tagesprofile",profileAssumption:"Die Kurven sind einfache Annahmen, keine gemessenen oder kalibrierten Verbrauchsmuster. Für alle Wochentage gilt dieselbe Kurve.",profileChartAria:"Vier Standard-Verbrauchskurven über die Tagesstunden",profileTable:"Anteil eines typischen Tages",hour:"Stunde",total:"Summe",profileDescription:{evening:"Nacht-Grundlast, Morgenspitze, niedrigerer Tagesverbrauch und deutliche Abendspitze.",mixed:"Verbrauch rund um die Uhr mit moderaten Morgen- und Abendspitzen.",daytime:"Niedriger Nachtverbrauch und ein größerer, gleichmäßig verteilter Anteil am Tag.",uniform:"In jedem Monat stündlich gleicher Verbrauch; die Monatsenergiemengen bleiben unterschiedlich."}},
  cs:{profileOverview:"Standardní denní profily",profileAssumption:"Křivky jsou jednoduché předpoklady, nikoli měřené nebo kalibrované vzorce spotřeby. Stejná křivka platí každý den v týdnu.",profileChartAria:"Čtyři standardní křivky spotřeby během dne",profileTable:"Podíl běžného dne",hour:"Hodina",total:"Celkem",profileDescription:{evening:"Noční základní odběr, ranní špička, nižší denní spotřeba a výrazná večerní špička.",mixed:"Spotřeba po celý den s mírnými ranními a večerními špičkami.",daytime:"Nízká noční spotřeba a větší rovnoměrný podíl během dne.",uniform:"Stejná spotřeba každou hodinu v měsíci; měsíční energie se stále liší."}},
  pl:{profileOverview:"Standardowe profile dobowe",profileAssumption:"Krzywe są prostymi założeniami, a nie zmierzonymi lub skalibrowanymi wzorcami zużycia. Ta sama krzywa obowiązuje każdego dnia tygodnia.",profileChartAria:"Cztery standardowe krzywe zużycia w ciągu doby",profileTable:"Udział typowej doby",hour:"Godzina",total:"Suma",profileDescription:{evening:"Nocne obciążenie bazowe, szczyt rano, niższe zużycie w dzień i wyraźny szczyt wieczorem.",mixed:"Zużycie przez całą dobę z umiarkowanymi szczytami rano i wieczorem.",daytime:"Niskie zużycie nocą i większy, równomierny udział w ciągu dnia.",uniform:"Takie samo zużycie w każdej godzinie miesiąca; miesięczne ilości energii nadal się różnią."}},
  sk:{profileOverview:"Štandardné denné profily",profileAssumption:"Krivky sú jednoduché predpoklady, nie merané ani kalibrované vzorce spotreby. Rovnaká krivka platí každý deň týždňa.",profileChartAria:"Štyri štandardné krivky spotreby počas dňa",profileTable:"Podiel bežného dňa",hour:"Hodina",total:"Spolu",profileDescription:{evening:"Nočný základný odber, ranná špička, nižšia denná spotreba a výrazná večerná špička.",mixed:"Spotreba počas celého dňa s miernymi rannými a večernými špičkami.",daytime:"Nízka nočná spotreba a väčší rovnomerný podiel cez deň.",uniform:"Rovnaká spotreba každú hodinu v mesiaci; mesačné energie sa stále líšia."}},
  sl:{profileOverview:"Standardni dnevni profili",profileAssumption:"Krivulje so preproste predpostavke, ne izmerjeni ali umerjeni vzorci porabe. Ista krivulja velja vse dni v tednu.",profileChartAria:"Štiri standardne krivulje porabe čez dan",profileTable:"Delež običajnega dne",hour:"Ura",total:"Skupaj",profileDescription:{evening:"Nočna osnovna poraba, jutranja konica, manjša dnevna poraba in jasna večerna konica.",mixed:"Poraba ves dan z zmernima jutranjo in večerno konico.",daytime:"Nizka nočna poraba in večji, enakomerno razporejen delež podnevi.",uniform:"Enaka poraba vsako uro v mesecu; mesečne količine energije ostanejo različne."}},
  et:{profileOverview:"Ööpäevased standardprofiilid",profileAssumption:"Kõverad on lihtsustatud eeldused, mitte mõõdetud ega kalibreeritud tarbimismustrid. Sama kõver kehtib igal nädalapäeval.",profileChartAria:"Neli ööpäevast tarbimise standardkõverat",profileTable:"Tavalise ööpäeva osakaal",hour:"Tund",total:"Kokku",profileDescription:{evening:"Öine baaskoormus, hommikune tipp, väiksem päevane tarbimine ja selge õhtune tipp.",mixed:"Tarbimine kogu päeva vältel mõõdukate hommiku- ja õhtutippudega.",daytime:"Väike öine tarbimine ning suurem ühtlane osakaal päeval.",uniform:"Igas kuu tunnis sama tarbimine; kuude energiakogused on siiski erinevad."}},
  lv:{profileOverview:"Diennakts standarta profili",profileAssumption:"Līknes ir vienkāršoti pieņēmumi, nevis mērīti vai kalibrēti patēriņa modeļi. Viena līkne tiek izmantota visām nedēļas dienām.",profileChartAria:"Četras standarta patēriņa līknes diennakts stundām",profileTable:"Parastas diennakts daļa",hour:"Stunda",total:"Kopā",profileDescription:{evening:"Nakts bāzes slodze, rīta maksimums, mazāks patēriņš dienā un skaidrs vakara maksimums.",mixed:"Patēriņš visu diennakti ar mēreniem rīta un vakara maksimumiem.",daytime:"Zems nakts patēriņš un lielāka, vienmērīga daļa dienā.",uniform:"Vienāds patēriņš katrā mēneša stundā; mēnešu enerģijas apjomi joprojām atšķiras."}},
  lt:{profileOverview:"Standartiniai paros profiliai",profileAssumption:"Kreivės yra paprastos prielaidos, o ne išmatuoti ar kalibruoti vartojimo modeliai. Ta pati kreivė taikoma kiekvieną savaitės dieną.",profileChartAria:"Keturios standartinės vartojimo kreivės per parą",profileTable:"Įprastos paros dalis",hour:"Valanda",total:"Iš viso",profileDescription:{evening:"Naktinė bazinė apkrova, rytinis pikas, mažesnis vartojimas dieną ir aiškus vakarinis pikas.",mixed:"Vartojimas visą parą su vidutiniais ryto ir vakaro pikais.",daytime:"Mažas naktinis vartojimas ir didesnė tolygiai paskirstyta dalis dieną.",uniform:"Vienodas vartojimas kiekvieną mėnesio valandą; mėnesio energijos kiekiai vis tiek skiriasi."}},
  fr:{profileOverview:"Profils journaliers types",profileAssumption:"Ces courbes sont des hypothèses simples, pas des profils de consommation mesurés ou étalonnés. La même courbe s’applique tous les jours.",profileChartAria:"Quatre courbes types de consommation sur une journée",profileTable:"Part d’une journée type",hour:"Heure",total:"Total",profileDescription:{evening:"Charge de base nocturne, pointe matinale, consommation plus faible en journée et pointe nette le soir.",mixed:"Consommation toute la journée avec des pointes modérées le matin et le soir.",daytime:"Faible consommation nocturne et part plus importante, répartie régulièrement en journée.",uniform:"Même consommation chaque heure du mois; les quantités mensuelles restent différentes."}},
  it:{profileOverview:"Profili giornalieri standard",profileAssumption:"Le curve sono ipotesi semplici, non modelli di consumo misurati o calibrati. La stessa curva viene usata ogni giorno della settimana.",profileChartAria:"Quattro curve standard del consumo nelle ore del giorno",profileTable:"Quota di un giorno tipico",hour:"Ora",total:"Totale",profileDescription:{evening:"Carico di base notturno, picco mattutino, minor consumo diurno e chiaro picco serale.",mixed:"Consumo durante tutto il giorno con picchi moderati al mattino e alla sera.",daytime:"Basso consumo notturno e quota maggiore, distribuita uniformemente di giorno.",uniform:"Stesso consumo in ogni ora del mese; le quantità mensili restano diverse."}},
  es:{profileOverview:"Perfiles diarios estándar",profileAssumption:"Las curvas son supuestos sencillos, no patrones de consumo medidos ni calibrados. Se usa la misma curva todos los días de la semana.",profileChartAria:"Cuatro curvas estándar de consumo durante el día",profileTable:"Parte de un día típico",hour:"Hora",total:"Total",profileDescription:{evening:"Carga base nocturna, pico matinal, menor consumo diurno y un pico claro por la tarde-noche.",mixed:"Consumo durante todo el día con picos moderados por la mañana y la tarde-noche.",daytime:"Bajo consumo nocturno y una mayor parte repartida uniformemente durante el día.",uniform:"El mismo consumo cada hora del mes; las cantidades mensuales siguen siendo diferentes."}},
  pt:{profileOverview:"Perfis diários padrão",profileAssumption:"As curvas são pressupostos simples, não padrões de consumo medidos ou calibrados. A mesma curva é usada todos os dias da semana.",profileChartAria:"Quatro curvas padrão de consumo ao longo do dia",profileTable:"Parcela de um dia típico",hour:"Hora",total:"Total",profileDescription:{evening:"Carga de base noturna, pico matinal, menor consumo diurno e pico claro ao fim do dia.",mixed:"Consumo ao longo do dia com picos moderados de manhã e ao fim do dia.",daytime:"Baixo consumo noturno e uma parcela maior, distribuída uniformemente durante o dia.",uniform:"O mesmo consumo em cada hora do mês; as quantidades mensais continuam diferentes."}},
  nl:{profileOverview:"Standaard dagprofielen",profileAssumption:"De curves zijn eenvoudige aannames, geen gemeten of gekalibreerde verbruikspatronen. Dezelfde curve geldt voor alle weekdagen.",profileChartAria:"Vier standaard verbruikscurves over de uren van een dag",profileTable:"Aandeel van een typische dag",hour:"Uur",total:"Totaal",profileDescription:{evening:"Nachtelijke basislast, ochtendpiek, lager dagverbruik en duidelijke avondpiek.",mixed:"Verbruik gedurende de hele dag met gematigde ochtend- en avondpieken.",daytime:"Laag nachtverbruik en een groter, gelijkmatig verdeeld aandeel overdag.",uniform:"Elk uur binnen een maand hetzelfde verbruik; maandtotalen blijven verschillend."}},
  no:{profileOverview:"Standardprofiler gjennom døgnet",profileAssumption:"Kurvene er enkle antakelser, ikke målte eller kalibrerte forbruksmønstre. Samme kurve brukes alle ukedager.",profileChartAria:"Fire standardkurver for forbruk gjennom døgnet",profileTable:"Andel av et normalt døgn",hour:"Time",total:"Sum",profileDescription:{evening:"Nattlig grunnlast, morgentopp, lavere forbruk på dagtid og tydelig kveldstopp.",mixed:"Forbruk hele døgnet med moderate morgen- og kveldstopper.",daytime:"Lavt nattforbruk og en større, jevnt fordelt andel på dagtid.",uniform:"Samme forbruk hver time i måneden; månedenes energimengder er fortsatt ulike."}},
  ro:{profileOverview:"Profiluri zilnice standard",profileAssumption:"Curbele sunt ipoteze simple, nu modele de consum măsurate sau calibrate. Aceeași curbă este folosită în fiecare zi a săptămânii.",profileChartAria:"Patru curbe standard de consum pe parcursul unei zile",profileTable:"Pondere dintr-o zi obișnuită",hour:"Oră",total:"Total",profileDescription:{evening:"Sarcină de bază nocturnă, vârf dimineața, consum mai mic ziua și vârf clar seara.",mixed:"Consum pe tot parcursul zilei, cu vârfuri moderate dimineața și seara.",daytime:"Consum redus noaptea și o pondere mai mare, distribuită uniform ziua.",uniform:"Același consum în fiecare oră a lunii; cantitățile lunare rămân diferite."}},
  el:{profileOverview:"Τυπικά ημερήσια προφίλ",profileAssumption:"Οι καμπύλες είναι απλές παραδοχές, όχι μετρημένα ή βαθμονομημένα πρότυπα κατανάλωσης. Η ίδια καμπύλη χρησιμοποιείται κάθε ημέρα.",profileChartAria:"Τέσσερις τυπικές καμπύλες κατανάλωσης στη διάρκεια της ημέρας",profileTable:"Ποσοστό μιας τυπικής ημέρας",hour:"Ώρα",total:"Σύνολο",profileDescription:{evening:"Νυχτερινό βασικό φορτίο, πρωινή αιχμή, χαμηλότερη ημερήσια κατανάλωση και σαφής βραδινή αιχμή.",mixed:"Κατανάλωση όλη την ημέρα με μέτριες πρωινές και βραδινές αιχμές.",daytime:"Χαμηλή νυχτερινή κατανάλωση και μεγαλύτερο, ομοιόμορφο μερίδιο την ημέρα.",uniform:"Ίδια κατανάλωση κάθε ώρα του μήνα· οι μηνιαίες ποσότητες ενέργειας παραμένουν διαφορετικές."}},
  hu:{profileOverview:"Napi szabványprofilok",profileAssumption:"A görbék egyszerű feltételezések, nem mért vagy kalibrált fogyasztási minták. A hét minden napján ugyanaz a görbe érvényes.",profileChartAria:"Négy napi szabványos fogyasztási görbe",profileTable:"Egy átlagos nap aránya",hour:"Óra",total:"Összesen",profileDescription:{evening:"Éjszakai alapterhelés, reggeli csúcs, alacsonyabb nappali fogyasztás és határozott esti csúcs.",mixed:"Egész napos fogyasztás mérsékelt reggeli és esti csúcsokkal.",daytime:"Alacsony éjszakai fogyasztás és nagyobb, egyenletes nappali rész.",uniform:"A hónap minden órájában azonos fogyasztás; a havi energiamennyiségek továbbra is eltérnek."}},
  hr:{profileOverview:"Standardni dnevni profili",profileAssumption:"Krivulje su jednostavne pretpostavke, a ne izmjereni ili kalibrirani obrasci potrošnje. Ista krivulja koristi se svaki dan u tjednu.",profileChartAria:"Četiri standardne krivulje potrošnje tijekom dana",profileTable:"Udio tipičnog dana",hour:"Sat",total:"Ukupno",profileDescription:{evening:"Noćno osnovno opterećenje, jutarnji vrh, niža dnevna potrošnja i jasan večernji vrh.",mixed:"Potrošnja tijekom cijelog dana s umjerenim jutarnjim i večernjim vrhovima.",daytime:"Niska noćna potrošnja i veći, ravnomjerno raspoređen udio danju.",uniform:"Ista potrošnja svakog sata u mjesecu; mjesečne količine energije i dalje se razlikuju."}},
  sr:{profileOverview:"Стандардни дневни профили",profileAssumption:"Криве су једноставне претпоставке, а не измерени или калибрисани обрасци потрошње. Иста крива се користи сваког дана.",profileChartAria:"Четири стандардне криве потрошње током дана",profileTable:"Удео типичног дана",hour:"Сат",total:"Укупно",profileDescription:{evening:"Ноћно основно оптерећење, јутарњи врх, нижа дневна потрошња и јасан вечерњи врх.",mixed:"Потрошња током целог дана са умереним јутарњим и вечерњим врховима.",daytime:"Ниска ноћна потрошња и већи, равномерно распоређен удео дању.",uniform:"Иста потрошња сваког сата у месецу; месечне количине енергије остају различите."}},
  bg:{profileOverview:"Стандартни дневни профили",profileAssumption:"Кривите са опростени допускания, а не измерени или калибрирани модели на потребление. Една и съща крива се използва всеки ден.",profileChartAria:"Четири стандартни криви на потребление през денонощието",profileTable:"Дял от типично денонощие",hour:"Час",total:"Общо",profileDescription:{evening:"Нощен базов товар, сутрешен пик, по-ниско дневно потребление и ясен вечерен пик.",mixed:"Потребление през целия ден с умерени сутрешни и вечерни пикове.",daytime:"Ниско нощно потребление и по-голям, равномерно разпределен дял през деня.",uniform:"Еднакво потребление всеки час от месеца; месечните количества енергия остават различни."}},
  uk:{profileOverview:"Стандартні добові профілі",profileAssumption:"Криві є простими припущеннями, а не виміряними чи каліброваними моделями споживання. Та сама крива використовується щодня.",profileChartAria:"Чотири стандартні криві споживання протягом доби",profileTable:"Частка типової доби",hour:"Година",total:"Разом",profileDescription:{evening:"Нічне базове навантаження, ранковий пік, нижче денне споживання та виразний вечірній пік.",mixed:"Споживання протягом усього дня з помірними ранковими та вечірніми піками.",daytime:"Низьке нічне споживання та більша, рівномірно розподілена частка вдень.",uniform:"Однакове споживання щогодини в межах місяця; місячні обсяги енергії залишаються різними."}},
  tr:{profileOverview:"Standart günlük profiller",profileAssumption:"Eğriler basit varsayımlardır; ölçülmüş veya kalibre edilmiş tüketim modelleri değildir. Haftanın her günü aynı eğri kullanılır.",profileChartAria:"Günün saatlerine yayılan dört standart tüketim eğrisi",profileTable:"Tipik bir günün payı",hour:"Saat",total:"Toplam",profileDescription:{evening:"Gece baz yükü, sabah zirvesi, daha düşük gündüz tüketimi ve belirgin akşam zirvesi.",mixed:"Gün boyunca orta düzeyde sabah ve akşam zirveleri olan tüketim.",daytime:"Düşük gece tüketimi ve gündüz eşit dağılan daha büyük pay.",uniform:"Ay içindeki her saatte aynı tüketim; aylık enerji miktarları yine farklıdır."}},
  hi:{profileOverview:"मानक दैनिक प्रोफ़ाइल",profileAssumption:"ये वक्र सरल अनुमान हैं, मापे या कैलिब्रेट किए गए खपत पैटर्न नहीं। सप्ताह के हर दिन एक ही वक्र उपयोग होता है।",profileChartAria:"दिन के घंटों में खपत के चार मानक वक्र",profileTable:"एक सामान्य दिन का हिस्सा",hour:"घंटा",total:"कुल",profileDescription:{evening:"रात का आधार भार, सुबह की चोटी, दिन में कम खपत और शाम की स्पष्ट चोटी।",mixed:"पूरे दिन खपत, सुबह और शाम मध्यम चोटियों के साथ।",daytime:"रात में कम खपत और दिन में बड़ा, समान रूप से फैला हिस्सा।",uniform:"महीने के हर घंटे समान खपत; मासिक ऊर्जा मात्रा फिर भी अलग रहती है।"}},
  id:{profileOverview:"Profil harian standar",profileAssumption:"Kurva ini adalah asumsi sederhana, bukan pola konsumsi terukur atau terkalibrasi. Kurva yang sama digunakan setiap hari.",profileChartAria:"Empat kurva konsumsi standar sepanjang hari",profileTable:"Porsi hari biasa",hour:"Jam",total:"Total",profileDescription:{evening:"Beban dasar malam, puncak pagi, konsumsi siang lebih rendah, dan puncak malam yang jelas.",mixed:"Konsumsi sepanjang hari dengan puncak sedang pada pagi dan malam.",daytime:"Konsumsi malam rendah dan porsi lebih besar yang merata pada siang hari.",uniform:"Konsumsi sama setiap jam dalam sebulan; jumlah energi bulanan tetap berbeda."}},
  he:{profileOverview:"פרופילים יומיים סטנדרטיים",profileAssumption:"העקומות הן הנחות פשוטות, לא דפוסי צריכה מדודים או מכוילים. אותה עקומה משמשת בכל ימות השבוע.",profileChartAria:"ארבע עקומות צריכה סטנדרטיות לאורך שעות היום",profileTable:"חלק מיום טיפוסי",hour:"שעה",total:"סך הכול",profileDescription:{evening:"עומס בסיס בלילה, שיא בוקר, צריכה נמוכה יותר ביום ושיא ערב ברור.",mixed:"צריכה לאורך כל היום עם שיאים מתונים בבוקר ובערב.",daytime:"צריכה נמוכה בלילה וחלק גדול ואחיד יותר בשעות היום.",uniform:"אותה צריכה בכל שעה בחודש; כמויות האנרגיה החודשיות עדיין שונות."}},
};