import io, os

T = {
"sv": ["Tillåten solcellseffekt (AC)","Begränsas av","Anslutningens kapacitet","Nationell solcellsregel","Andel av anslutningens kapacitet","Backfeed-/samlingsskeneregel",
 "Anläggningens storlek styrs av ditt lands regler för solcellsanslutning, inte av huvudsäkringen.",
 "Anläggningens storlek styrs av backfeed-regeln för din elcentral, inte av huvudsäkringen.",
 "Anläggningar över {{limit}} kW omfattas inte av den förenklade anslutningsprocessen. Systemet är fortfarande möjligt, men kräver normalt ansökan och godkännande från din nätägare."],
"en": ["Allowed PV power (AC)","Limited by","Connection capacity","National PV rule","Share of connection capacity","Busbar/backfeed rule",
 "The system size is set by your country's PV connection rule, not by the main fuse.",
 "The system size is set by the busbar/backfeed rule for your service panel, not by the main fuse.",
 "Systems above {{limit}} kW fall outside the simplified connection process. The system is still possible, but normally requires an application and approval from your grid operator."],
"fi": ["Sallittu aurinkosähkön teho (AC)","Rajoittava tekijä","Liittymän kapasiteetti","Kansallinen aurinkosähkösääntö","Osuus liittymän kapasiteetista","Kiskosto-/takasyöttösääntö",
 "Järjestelmän koon määrää maasi aurinkosähkön liittymissääntö, ei pääsulake.",
 "Järjestelmän koon määrää sähkökeskuksesi takasyöttösääntö, ei pääsulake.",
 "Yli {{limit}} kW:n järjestelmät eivät kuulu yksinkertaistettuun liittymismenettelyyn. Järjestelmä on yhä mahdollinen, mutta se edellyttää yleensä hakemusta ja verkkoyhtiön hyväksyntää."],
"da": ["Tilladt solcelleeffekt (AC)","Begrænses af","Tilslutningens kapacitet","National solcelleregel","Andel af tilslutningens kapacitet","Skinne-/tilbagefødningsregel",
 "Anlæggets størrelse bestemmes af dit lands regler for solcelletilslutning, ikke af hovedsikringen.",
 "Anlæggets størrelse bestemmes af tilbagefødningsreglen for din eltavle, ikke af hovedsikringen.",
 "Anlæg over {{limit}} kW er ikke omfattet af den forenklede tilslutningsproces. Anlægget er stadig muligt, men kræver normalt ansøgning og godkendelse fra dit netselskab."],
"de": ["Zulässige PV-Leistung (AC)","Begrenzt durch","Anschlusskapazität","Nationale PV-Regel","Anteil der Anschlusskapazität","Sammelschienen-/Rückspeiseregel",
 "Die Anlagengröße wird durch die PV-Anschlussregel Ihres Landes bestimmt, nicht durch die Hauptsicherung.",
 "Die Anlagengröße wird durch die Rückspeiseregel Ihrer Verteilung bestimmt, nicht durch die Hauptsicherung.",
 "Anlagen über {{limit}} kW fallen nicht unter das vereinfachte Anschlussverfahren. Die Anlage ist weiterhin möglich, erfordert aber in der Regel einen Antrag und die Zustimmung Ihres Netzbetreibers."],
"cs": ["Povolený výkon FV (AC)","Omezeno","Kapacita přípojky","Národní pravidlo pro FV","Podíl kapacity přípojky","Pravidlo přípojnice / zpětného napájení",
 "Velikost systému určuje národní pravidlo pro připojení FV, nikoli hlavní jistič.",
 "Velikost systému určuje pravidlo zpětného napájení vašeho rozváděče, nikoli hlavní jistič.",
 "Systémy nad {{limit}} kW nespadají do zjednodušeného procesu připojení. Systém je stále možný, obvykle však vyžaduje žádost a souhlas provozovatele distribuční soustavy."],
"pl": ["Dozwolona moc PV (AC)","Ograniczone przez","Moc przyłącza","Krajowa zasada dla PV","Udział mocy przyłącza","Zasada szyny / oddawania mocy",
 "Wielkość instalacji wynika z krajowych zasad przyłączania PV, a nie z bezpiecznika głównego.",
 "Wielkość instalacji wynika z zasady oddawania mocy w rozdzielnicy, a nie z bezpiecznika głównego.",
 "Instalacje powyżej {{limit}} kW nie podlegają uproszczonej procedurze przyłączenia. Instalacja jest nadal możliwa, ale zwykle wymaga wniosku i zgody operatora sieci."],
"sk": ["Povolený výkon FV (AC)","Obmedzené","Kapacita prípojky","Národné pravidlo pre FV","Podiel kapacity prípojky","Pravidlo prípojnice / spätného napájania",
 "Veľkosť systému určuje národné pravidlo pripojenia FV, nie hlavný istič.",
 "Veľkosť systému určuje pravidlo spätného napájania vášho rozvádzača, nie hlavný istič.",
 "Systémy nad {{limit}} kW nespadajú do zjednodušeného procesu pripojenia. Systém je stále možný, zvyčajne však vyžaduje žiadosť a súhlas prevádzkovateľa siete."],
"sl": ["Dovoljena moč sončne elektrarne (AC)","Omejeno z","Zmogljivost priključka","Nacionalno pravilo za sončne elektrarne","Delež zmogljivosti priključka","Pravilo zbiralke / vračanja energije",
 "Velikost sistema določa nacionalno pravilo za priklop sončne elektrarne, ne glavna varovalka.",
 "Velikost sistema določa pravilo vračanja energije v vaši omarici, ne glavna varovalka.",
 "Sistemi nad {{limit}} kW niso zajeti v poenostavljenem postopku priklopa. Sistem je še vedno mogoč, a običajno zahteva vlogo in soglasje operaterja omrežja."],
"et": ["Lubatud päikeseenergia võimsus (AC)","Piirab","Liitumise võimsus","Riiklik päikeseenergia reegel","Osa liitumisvõimsusest","Kogumislati / tagasisöötmise reegel",
 "Süsteemi suuruse määrab riigi päikeseelektri liitumisreegel, mitte peakaitse.",
 "Süsteemi suuruse määrab teie jaotuskilbi tagasisöötmise reegel, mitte peakaitse.",
 "Üle {{limit}} kW süsteemid ei kuulu lihtsustatud liitumisprotsessi alla. Süsteem on endiselt võimalik, kuid eeldab tavaliselt taotlust ja võrguettevõtja nõusolekut."],
"lv": ["Atļautā saules jauda (AC)","Ierobežo","Pieslēguma jauda","Nacionālais saules enerģijas noteikums","Daļa no pieslēguma jaudas","Kopnes / atpakaļpadeves noteikums",
 "Sistēmas lielumu nosaka valsts saules enerģijas pieslēguma noteikums, nevis galvenais drošinātājs.",
 "Sistēmas lielumu nosaka jūsu sadalnes atpakaļpadeves noteikums, nevis galvenais drošinātājs.",
 "Sistēmām, kas pārsniedz {{limit}} kW, vienkāršotā pieslēguma kārtība nav piemērojama. Sistēma joprojām ir iespējama, taču parasti nepieciešams iesniegums un tīkla operatora piekrišana."],
"lt": ["Leistina saulės elektrinės galia (AC)","Riboja","Prijungimo galia","Nacionalinė saulės elektrinių taisyklė","Prijungimo galios dalis","Šynos / atgalinio tiekimo taisyklė",
 "Sistemos dydį lemia šalies saulės elektrinių prijungimo taisyklė, o ne pagrindinis saugiklis.",
 "Sistemos dydį lemia jūsų skydo atgalinio tiekimo taisyklė, o ne pagrindinis saugiklis.",
 "Didesnėms nei {{limit}} kW sistemoms supaprastinta prijungimo tvarka netaikoma. Sistema vis tiek galima, tačiau paprastai reikia paraiškos ir tinklo operatoriaus pritarimo."],
"fr": ["Puissance PV autorisée (AC)","Limité par","Capacité du raccordement","Règle nationale PV","Part de la capacité de raccordement","Règle de jeu de barres / réinjection",
 "La taille de l'installation est fixée par la règle nationale de raccordement PV, et non par le disjoncteur principal.",
 "La taille de l'installation est fixée par la règle de réinjection de votre tableau, et non par le disjoncteur principal.",
 "Les installations de plus de {{limit}} kW ne relèvent pas de la procédure simplifiée de raccordement. L'installation reste possible, mais nécessite normalement une demande et l'accord de votre gestionnaire de réseau."],
"it": ["Potenza FV consentita (AC)","Limitato da","Capacità della connessione","Regola nazionale FV","Quota della capacità di connessione","Regola della sbarra / reimmissione",
 "La dimensione dell'impianto è determinata dalla regola nazionale di connessione FV, non dall'interruttore generale.",
 "La dimensione dell'impianto è determinata dalla regola di reimmissione del tuo quadro, non dall'interruttore generale.",
 "Gli impianti oltre {{limit}} kW non rientrano nella procedura semplificata di connessione. L'impianto resta possibile, ma richiede di norma una domanda e l'approvazione del gestore di rete."],
"es": ["Potencia FV permitida (AC)","Limitado por","Capacidad de la conexión","Norma nacional FV","Porcentaje de la capacidad de conexión","Regla de embarrado / reinyección",
 "El tamaño de la instalación lo fija la norma nacional de conexión FV, no el interruptor general.",
 "El tamaño de la instalación lo fija la regla de reinyección de tu cuadro, no el interruptor general.",
 "Las instalaciones de más de {{limit}} kW quedan fuera del procedimiento simplificado de conexión. La instalación sigue siendo posible, pero normalmente requiere solicitud y aprobación de tu distribuidora."],
"pt": ["Potência FV permitida (AC)","Limitado por","Capacidade da ligação","Regra nacional FV","Parte da capacidade de ligação","Regra do barramento / injeção",
 "A dimensão do sistema é definida pela regra nacional de ligação FV, não pelo disjuntor principal.",
 "A dimensão do sistema é definida pela regra de injeção do seu quadro, não pelo disjuntor principal.",
 "Sistemas acima de {{limit}} kW ficam fora do processo simplificado de ligação. O sistema continua possível, mas exige normalmente pedido e aprovação do operador de rede."],
"nl": ["Toegestaan pv-vermogen (AC)","Beperkt door","Capaciteit van de aansluiting","Nationale pv-regel","Aandeel van de aansluitcapaciteit","Rail-/terugleveringsregel",
 "De omvang van het systeem wordt bepaald door de nationale pv-aansluitregel, niet door de hoofdzekering.",
 "De omvang van het systeem wordt bepaald door de terugleveringsregel van uw verdeelkast, niet door de hoofdzekering.",
 "Systemen boven {{limit}} kW vallen buiten de vereenvoudigde aansluitprocedure. Het systeem blijft mogelijk, maar vereist doorgaans een aanvraag en goedkeuring van uw netbeheerder."],
"no": ["Tillatt solcelleeffekt (AC)","Begrenses av","Tilknytningens kapasitet","Nasjonal solcelleregel","Andel av tilknytningens kapasitet","Skinne-/tilbakemateregel",
 "Anleggets størrelse bestemmes av landets regler for solcelletilknytning, ikke av hovedsikringen.",
 "Anleggets størrelse bestemmes av tilbakemateregelen for sikringsskapet ditt, ikke av hovedsikringen.",
 "Anlegg over {{limit}} kW omfattes ikke av den forenklede tilknytningsprosessen. Anlegget er fortsatt mulig, men krever normalt søknad og godkjenning fra nettselskapet."],
"ro": ["Putere FV permisă (AC)","Limitat de","Capacitatea racordului","Regulă națională FV","Cotă din capacitatea racordului","Regula barei / injecției inverse",
 "Dimensiunea sistemului este stabilită de regula națională de racordare FV, nu de siguranța generală.",
 "Dimensiunea sistemului este stabilită de regula de injecție a tabloului dvs., nu de siguranța generală.",
 "Sistemele de peste {{limit}} kW nu intră în procedura simplificată de racordare. Sistemul rămâne posibil, dar necesită de regulă o cerere și aprobarea operatorului de rețea."],
"el": ["Επιτρεπόμενη ισχύς Φ/Β (AC)","Περιορίζεται από","Ισχύς σύνδεσης","Εθνικός κανόνας Φ/Β","Ποσοστό της ισχύος σύνδεσης","Κανόνας ζυγού / έγχυσης",
 "Το μέγεθος του συστήματος καθορίζεται από τον εθνικό κανόνα σύνδεσης Φ/Β, όχι από τη γενική ασφάλεια.",
 "Το μέγεθος του συστήματος καθορίζεται από τον κανόνα έγχυσης του πίνακά σας, όχι από τη γενική ασφάλεια.",
 "Συστήματα άνω των {{limit}} kW δεν εμπίπτουν στην απλοποιημένη διαδικασία σύνδεσης. Το σύστημα παραμένει εφικτό, αλλά συνήθως απαιτεί αίτηση και έγκριση του διαχειριστή δικτύου."],
"hu": ["Engedélyezett napelemes teljesítmény (AC)","Korlátozza","A csatlakozás kapacitása","Nemzeti napelemes szabály","A csatlakozási kapacitás hányada","Gyűjtősín / visszatáplálási szabály",
 "A rendszer méretét az ország napelemes csatlakozási szabálya határozza meg, nem a főbiztosíték.",
 "A rendszer méretét az elosztószekrény visszatáplálási szabálya határozza meg, nem a főbiztosíték.",
 "A {{limit}} kW feletti rendszerek nem tartoznak az egyszerűsített csatlakozási eljárás alá. A rendszer továbbra is lehetséges, de általában kérelmet és hálózati engedélyt igényel."],
"hr": ["Dopuštena snaga FN (AC)","Ograničeno","Kapacitet priključka","Nacionalno pravilo za FN","Udio kapaciteta priključka","Pravilo sabirnice / povratnog napajanja",
 "Veličinu sustava određuje nacionalno pravilo priključenja FN, a ne glavni osigurač.",
 "Veličinu sustava određuje pravilo povratnog napajanja vašeg razdjelnika, a ne glavni osigurač.",
 "Sustavi iznad {{limit}} kW nisu obuhvaćeni pojednostavljenim postupkom priključenja. Sustav je i dalje moguć, ali obično zahtijeva zahtjev i odobrenje operatora mreže."],
"sr": ["Dozvoljena snaga solarne elektrane (AC)","Ograničeno","Kapacitet priključka","Nacionalno pravilo za solarne elektrane","Udeo kapaciteta priključka","Pravilo sabirnice / povratnog napajanja",
 "Veličinu sistema određuje nacionalno pravilo priključenja solarne elektrane, a ne glavni osigurač.",
 "Veličinu sistema određuje pravilo povratnog napajanja vašeg razvodnog ormana, a ne glavni osigurač.",
 "Sistemi preko {{limit}} kW nisu obuhvaćeni pojednostavljenim postupkom priključenja. Sistem je i dalje moguć, ali obično zahteva zahtev i odobrenje operatora mreže."],
"bg": ["Допустима мощност на ФЕЦ (AC)","Ограничено от","Капацитет на присъединяването","Национално правило за ФЕЦ","Дял от капацитета на присъединяването","Правило за шина / обратно захранване",
 "Размерът на системата се определя от националното правило за присъединяване на ФЕЦ, а не от главния предпазител.",
 "Размерът на системата се определя от правилото за обратно захранване на вашето табло, а не от главния предпазител.",
 "Системи над {{limit}} kW не попадат в опростената процедура за присъединяване. Системата остава възможна, но обикновено изисква заявление и одобрение от мрежовия оператор."],
"uk": ["Дозволена потужність СЕС (AC)","Обмежено","Потужність приєднання","Національне правило для СЕС","Частка потужності приєднання","Правило шини / зворотної подачі",
 "Розмір системи визначається національним правилом приєднання СЕС, а не головним запобіжником.",
 "Розмір системи визначається правилом зворотної подачі вашого щита, а не головним запобіжником.",
 "Системи понад {{limit}} кВт не підпадають під спрощену процедуру приєднання. Система все ще можлива, але зазвичай потребує заяви та погодження оператора мережі."],
"tr": ["İzin verilen GES gücü (AC)","Sınırlayan","Bağlantı kapasitesi","Ulusal GES kuralı","Bağlantı kapasitesinin payı","Bara / geri besleme kuralı",
 "Sistem büyüklüğünü ana sigorta değil, ülkenizin GES bağlantı kuralı belirler.",
 "Sistem büyüklüğünü ana sigorta değil, panonuzun geri besleme kuralı belirler.",
 "{{limit}} kW üzerindeki sistemler basitleştirilmiş bağlantı sürecinin dışında kalır. Sistem yine de mümkündür, ancak genellikle şebeke işletmecisinden başvuru ve onay gerektirir."],
"hi": ["अनुमत सोलर क्षमता (AC)","सीमित करने वाला","कनेक्शन की क्षमता","राष्ट्रीय सोलर नियम","कनेक्शन क्षमता का हिस्सा","बसबार / बैकफीड नियम",
 "सिस्टम का आकार आपके देश के सोलर कनेक्शन नियम से तय होता है, मुख्य फ्यूज़ से नहीं।",
 "सिस्टम का आकार आपके पैनल के बैकफीड नियम से तय होता है, मुख्य फ्यूज़ से नहीं।",
 "{{limit}} kW से बड़े सिस्टम सरलीकृत कनेक्शन प्रक्रिया में नहीं आते। सिस्टम फिर भी संभव है, पर आमतौर पर ग्रिड ऑपरेटर से आवेदन और स्वीकृति आवश्यक होती है।"],
"id": ["Daya PLTS yang diizinkan (AC)","Dibatasi oleh","Kapasitas sambungan","Aturan PLTS nasional","Porsi kapasitas sambungan","Aturan busbar / backfeed",
 "Ukuran sistem ditentukan oleh aturan sambungan PLTS di negara Anda, bukan oleh sekring utama.",
 "Ukuran sistem ditentukan oleh aturan backfeed panel listrik Anda, bukan oleh sekring utama.",
 "Sistem di atas {{limit}} kW berada di luar proses sambungan yang disederhanakan. Sistem tetap memungkinkan, tetapi biasanya memerlukan permohonan dan persetujuan operator jaringan."],
"he": ["הספק סולארי מותר (AC)","מוגבל על ידי","קיבולת החיבור","כלל סולארי לאומי","חלק מקיבולת החיבור","כלל פס צבירה / הזרמה חוזרת",
 "גודל המערכת נקבע על ידי כללי החיבור הסולאריים במדינה שלכם, ולא על ידי המאמ\"ת הראשי.",
 "גודל המערכת נקבע על ידי כלל ההזרמה החוזרת בלוח החשמל שלכם, ולא על ידי המאמ\"ת הראשי.",
 "מערכות מעל {{limit}} kW אינן נכללות בתהליך החיבור המפושט. המערכת עדיין אפשרית, אך בדרך כלל נדרשת בקשה ואישור מחברת החשמל."],
}

NAMES = ["pvLimitLabel","bindingLimitLabel","bindingConnectionCapacity","bindingPvRule",
         "bindingCapacityShare","bindingBusbar","reasonPvRuleLimit","reasonBusbarLimit",
         "simplifiedProcessNote"]

for lang, values in T.items():
    path = f"src/i18n/locales/{lang}.ts"
    src = open(path, encoding="utf-8").read()
    assert "\n    summerShare:" in src, lang
    if "pvLimitLabel:" in src:
        continue
    block = "".join(
        f'    {name}:\n      {values[i]!r},\n'.replace("'", '"') if False else
        f'    {name}: {tsstr(values[i])},\n'
        for i, name in enumerate(NAMES)
    )
    src = src.replace("\n    summerShare:", "\n" + block + "    summerShare:", 1)
    open(path, "w", encoding="utf-8").write(src)
