/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnvandarvillkorRouteImport } from './routes/anvandarvillkor'
import { Route as BetalningRouteImport } from './routes/betalning'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as ResultatRouteImport } from './routes/resultat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnvandarvillkorRoute = AnvandarvillkorRouteImport.update({
  id: '/anvandarvillkor',
  path: '/anvandarvillkor',
  getParentRoute: () => rootRouteImport,
} as any)
const BetalningRoute = BetalningRouteImport.update({
  id: '/betalning',
  path: '/betalning',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatRoute = ResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anvandarvillkor': typeof AnvandarvillkorRoute
  '/betalning': typeof BetalningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/resultat': typeof ResultatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anvandarvillkor': typeof AnvandarvillkorRoute
  '/betalning': typeof BetalningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/resultat': typeof ResultatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anvandarvillkor': typeof AnvandarvillkorRoute
  '/betalning': typeof BetalningRoute
  '/historik': typeof HistorikRoute
  '/installningar': typeof InstallningarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/resultat': typeof ResultatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anvandarvillkor'
    | '/betalning'
    | '/historik'
    | '/installningar'
    | '/integritetspolicy'
    | '/resultat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anvandarvillkor'
    | '/betalning'
    | '/historik'
    | '/installningar'
    | '/integritetspolicy'
    | '/resultat'
  id:
    | '__root__'
    | '/'
    | '/anvandarvillkor'
    | '/betalning'
    | '/historik'
    | '/installningar'
    | '/integritetspolicy'
    | '/resultat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnvandarvillkorRoute: typeof AnvandarvillkorRoute
  BetalningRoute: typeof BetalningRoute
  HistorikRoute: typeof HistorikRoute
  InstallningarRoute: typeof InstallningarRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  ResultatRoute: typeof ResultatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anvandarvillkor': {
      id: '/anvandarvillkor'
      path: '/anvandarvillkor'
      fullPath: '/anvandarvillkor'
      preLoaderRoute: typeof AnvandarvillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betalning': {
      id: '/betalning'
      path: '/betalning'
      fullPath: '/betalning'
      preLoaderRoute: typeof BetalningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat': {
      id: '/resultat'
      path: '/resultat'
      fullPath: '/resultat'
      preLoaderRoute: typeof ResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnvandarvillkorRoute: AnvandarvillkorRoute,
  BetalningRoute: BetalningRoute,
  HistorikRoute: HistorikRoute,
  InstallningarRoute: InstallningarRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  ResultatRoute: ResultatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
